CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE accounts (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    email character varying(256),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    site_id integer NOT NULL,
    CONSTRAINT p_k_accounts PRIMARY KEY (id)
);

CREATE TABLE sites (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    name character varying(200) NOT NULL,
    description character varying(500),
    CONSTRAINT p_k_sites PRIMARY KEY (id),
    CONSTRAINT "FK_Site_Account" FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE TABLE web_sessions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    CONSTRAINT p_k_web_session_entity PRIMARY KEY (id),
    CONSTRAINT "FK_WebSessions_Account" FOREIGN KEY (account_id) REFERENCES accounts (id)
);

CREATE TABLE processes (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    name character varying(200) NOT NULL,
    status character varying(50),
    started_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    site_id integer NOT NULL,
    account_entity_id integer,
    CONSTRAINT p_k_process_entity PRIMARY KEY (id),
    CONSTRAINT "FK_Process_Site" FOREIGN KEY (site_id) REFERENCES sites (id),
    CONSTRAINT f_k_process_entity_accounts_account_entity_id FOREIGN KEY (account_entity_id) REFERENCES accounts (id)
);

CREATE TABLE secrets (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    site_id integer NOT NULL,
    name character varying(200) NOT NULL,
    hash character varying(500) NOT NULL,
    CONSTRAINT p_k_secrets PRIMARY KEY (id),
    CONSTRAINT "FK_Secret_Site" FOREIGN KEY (site_id) REFERENCES sites (id) ON DELETE CASCADE
);

CREATE TABLE web_subscriptions (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    session_id integer NOT NULL,
    process_id integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    renewed_at timestamp with time zone NOT NULL,
    CONSTRAINT p_k_web_subscriptions PRIMARY KEY (id),
    CONSTRAINT "FK_WebSubscriptions_Process" FOREIGN KEY (process_id) REFERENCES processes (id),
    CONSTRAINT "FK_WebSubscriptions_Session" FOREIGN KEY (session_id) REFERENCES web_sessions (id)
);

CREATE INDEX i_x_process_entity_account_entity_id ON processes (account_entity_id);

CREATE INDEX i_x_process_entity_site_id ON processes (site_id);

CREATE INDEX i_x_secrets_site_id ON secrets (site_id);

CREATE INDEX i_x_sites_account_id ON sites (account_id);

CREATE INDEX i_x_web_session_entity_account_id ON web_sessions (account_id);

CREATE INDEX i_x_web_subscriptions_process_id ON web_subscriptions (process_id);

CREATE INDEX i_x_web_subscriptions_session_id ON web_subscriptions (session_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260212234015_Initial', '10.0.2');

COMMIT;

