// <auto-generated />
using System;
using DiagnosticExplorer.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(DiagDbContext))]
    partial class DiagDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("p_k_accounts");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.ProcessEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountEntityId")
                        .HasColumnType("integer")
                        .HasColumnName("account_entity_id");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("connection_id");

                    b.Property<string>("InstanceId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("instance_id");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean")
                        .HasColumnName("is_online");

                    b.Property<bool>("IsSending")
                        .HasColumnType("boolean")
                        .HasColumnName("is_sending");

                    b.Property<DateTime>("LastOnline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_online");

                    b.Property<DateTime>("LastReceived")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_received");

                    b.Property<string>("MachineName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("machine_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_k_processes");

                    b.HasIndex("AccountEntityId")
                        .HasDatabaseName("i_x_processes_account_entity_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_processes_site_id");

                    b.ToTable("processes", (string)null);
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.SecretEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("site_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("p_k_secrets");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_secrets_site_id");

                    b.ToTable("secrets", (string)null);
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.SiteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_k_sites");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_sites_account_id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.WebSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer")
                        .HasColumnName("account_id");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("connection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("p_k_web_sessions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("i_x_web_sessions_account_id");

                    b.HasIndex("ConnectionId")
                        .IsUnique();

                    b.ToTable("web_sessions", (string)null);
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.WebSubcriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer")
                        .HasColumnName("process_id");

                    b.Property<DateTime>("RenewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewed_at");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("p_k_web_subscriptions");

                    b.HasIndex("ProcessId")
                        .HasDatabaseName("i_x_web_subscriptions_process_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("i_x_web_subscriptions_session_id");

                    b.HasIndex("SessionId", "ProcessId")
                        .IsUnique();

                    b.ToTable("web_subscriptions", (string)null);
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.ProcessEntity", b =>
                {
                    b.HasOne("DiagnosticExplorer.DataAccess.Entities.AccountEntity", null)
                        .WithMany("Processes")
                        .HasForeignKey("AccountEntityId")
                        .HasConstraintName("f_k_processes_accounts_account_entity_id");

                    b.HasOne("DiagnosticExplorer.DataAccess.Entities.SiteEntity", "Site")
                        .WithMany("Processes")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("f_k_processes__sites_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.SecretEntity", b =>
                {
                    b.HasOne("DiagnosticExplorer.DataAccess.Entities.SiteEntity", "Site")
                        .WithMany("Secrets")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Secret_Site");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.SiteEntity", b =>
                {
                    b.HasOne("DiagnosticExplorer.DataAccess.Entities.AccountEntity", "Account")
                        .WithMany("Sites")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_Site_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.WebSessionEntity", b =>
                {
                    b.HasOne("DiagnosticExplorer.DataAccess.Entities.AccountEntity", "Account")
                        .WithMany("Sessions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_WebSessions_Account");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.WebSubcriptionEntity", b =>
                {
                    b.HasOne("DiagnosticExplorer.DataAccess.Entities.ProcessEntity", "Process")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_WebSubscriptions_Process");

                    b.HasOne("DiagnosticExplorer.DataAccess.Entities.WebSessionEntity", "Session")
                        .WithMany("Subscriptions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("FK_WebSubscriptions_Session");

                    b.Navigation("Process");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.AccountEntity", b =>
                {
                    b.Navigation("Processes");

                    b.Navigation("Sessions");

                    b.Navigation("Sites");
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.ProcessEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.SiteEntity", b =>
                {
                    b.Navigation("Processes");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("DiagnosticExplorer.DataAccess.Entities.WebSessionEntity", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
